apiVersion: terraformcontroller.cattle.io/v1
kind: State
metadata:
  name: my-state
spec:
  moduleName: my-module
  destroyOnDelete: true
  autoConfirm: true
  image: rancher/terraform-controller-executor:v0.0.12-alpha1
  variables:
    secretNames:
      - mysecret
    envConfigNames:
      - env-config
